services:
  minecraft1:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VIEW_DISTANCE: 15
      MEMORY: 2G
      MOTD: "Minecraft but wayyyy harder :)"
      ICON: https://static.wikia.nocookie.net/geometry-dash-unofficial/images/3/36/Extreme_Demon.png/revision/latest?cb=20180214082927
      TYPE: SPIGOT
      VERSION: "1.21"
    ports:
      - "25565:25565"
    volumes:
      - data1:/data
      - ./ops.json:/data/ops.json
      - ./custom-entrypoint.sh:/custom-entrypoint.sh
    entrypoint: ["/bin/bash", "/custom-entrypoint.sh"]

  # This is an example of a second Minecraft server, you can uncomment it if you want to run a second server
  # minecraft2:
  #   image: itzg/minecraft-server
  #   environment:
  #     EULA: "true"
  #     VIEW_DISTANCE: 15
  #     MEMORY: 2G
  #     MOTD: "Another Minecraft Server"
  #     TYPE: SPIGOT
  #     VERSION: "1.21"
  #   ports:
  #     - "25566:25565"
  #   volumes:
  #     - data2:/data
  #     - ./ops.json:/data/ops.json
  #     - ./custom-entrypoint.sh:/custom-entrypoint.sh
  #   entrypoint: ["/bin/bash", "/custom-entrypoint.sh"]

  ngrok1:
    image: ngrok/ngrok
    command: ["tcp", "minecraft1:25565", "--log", "stdout", "--authtoken", "${NGROK_AUTH}"]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH}
    depends_on:
      - minecraft1

  # This is an example of a second ngrok tunnel, this requires upgrading ngrok account to a paid tier to run multiple tunnels
  # ngrok2:
  #   image: ngrok/ngrok
  #   command: ["tcp", "minecraft2:25565", "--log", "stdout", "--authtoken", "${NGROK_AUTH}"]
  #   environment:
  #     - NGROK_AUTHTOKEN=${NGROK_AUTH}
  #   depends_on:
  #     - minecraft2

volumes:
  data1: {}
  # data2: {}