services:
  minecraft1:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VIEW_DISTANCE: 15
      MEMORY: 2G
      MOTD: "Minecraft but wayyyy harder :)"
      ICON: https://static.wikia.nocookie.net/geometry-dash-unofficial/images/3/36/Extreme_Demon.png/revision/latest?cb=20180214082927
      TYPE: SPIGOT
      VERSION: "1.21"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./ops.json:/data/ops.json
      - ./custom-entrypoint.sh:/custom-entrypoint.sh
    entrypoint: ["/bin/bash", "/custom-entrypoint.sh"]

  ngrok:
    image: ngrok/ngrok
    command: ["tcp", "minecraft1:25565", "--log", "stdout", "--authtoken", "${NGROK_AUTH}"]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH}
    depends_on:
      - minecraft1

volumes:
  data: {}